services:
  dualbot:
    image: dualbot_ubuntu24
    container_name: dualbot_jazzy_ws
    network_mode: host
    privileged: true
    ipc: host
    tty: true
    stdin_open: true
    environment:
      ROS_DISTRO: jazzy
      ROS_DOMAIN_ID: 42
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      QT_X11_NO_MITSHM: "1"
      DISPLAY: ${DISPLAY}
      XAUTHORITY: /root/.Xauthority
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        ROS_DISTRO: jazzy
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../ws:/ws/
      - /dev:/dev
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
    working_dir: /ws
    command: bash 